<a href="https://colab.research.google.com/github/rkoirala129/nlp/blob/main/basic_vect/One_hot_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Without Scikit-Learn**

In [ ]:
!pip install scikit-learn


In [ ]:
mydocs = ["Welcome to NLP world.","NLP is great","World is ugly and sad."]
mydocs_process = [doc.lower().replace(".","") for doc in mydocs]
mydocs_process

['welcome to nlp world', 'nlp is great', 'world is ugly and sad']

In [ ]:
myvocab = {}
count = 0
for doc in mydocs_process:
    for word in doc.split():
        if word not in myvocab:
            count = count +1
            myvocab[word] = count
print(myvocab)

{'welcome': 1, 'to': 2, 'nlp': 3, 'world': 4, 'is': 5, 'great': 6, 'ugly': 7, 'and': 8, 'sad': 9}


In [ ]:
def derive_onehot_vector(anystring):
    onehot_encoded = []
    for word in anystring.split():
        temp = [0]*len(myvocab)
        if word in myvocab:
            temp[myvocab[word]-1] = 1 # -1 is to take care of the fact indexing in array starts from 0 and not 1
        onehot_encoded.append(temp)
    return onehot_encoded

In [ ]:
print(mydocs_process[0])
derive_onehot_vector(mydocs_process[0]) 

welcome to nlp world


[[1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 0]]

In [ ]:
derive_onehot_vector("I am the world")#those words that are not available in the vocabulary will return vector with only 0's.

[[0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 0]]

**With Scikit Learn**

In [15]:
d1 = "Welcome to NLP young man."
d2 = "NLP is great"
d3 = "World is ugly."

In [16]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

data = [d1.split(), d2.split(), d3.split()]
values = data[0]+data[1]+data[2]
print("The data: ",values)


The data:  ['Welcome', 'to', 'NLP', 'young', 'man.', 'NLP', 'is', 'great', 'World', 'is', 'ugly.']


In [18]:
import numpy
arr = numpy.array(values)
arr


array(['Welcome', 'to', 'NLP', 'young', 'man.', 'NLP', 'is', 'great',
       'World', 'is', 'ugly.'], dtype='<U7')

In [19]:
#Label Encoding
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print("Label Encoded:",integer_encoded)

Label Encoded: [1 6 0 8 5 0 4 3 2 4 7]


In [21]:
#One-Hot Encoding

onehot_encoder = OneHotEncoder()
onehot_encoded = onehot_encoder.fit_transform(arr.reshape(-1,1)).toarray()
print("Onehot Encoded Matrix:\n",onehot_encoded)

Onehot Encoded Matrix:
 [[0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]]
